name: rdsdms
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  #Get X => State Management
  get: ^3.26.0

  #Json_annotation => Generate Model
  json_annotation: ^3.1.1

  #Http => Http Method
  http: ^0.12.2

  #persistent_bottom_nav_bar => Bottom Tab Bar
  persistent_bottom_nav_bar: ^3.1.0

  #fl_chart => Draw chart
  fl_chart: ^0.12.3

  #google_maps_flutter => Add Map
  google_maps_flutter: ^1.2.0

  location: ^3.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  json_serializable: ^3.5.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
